services:
  ubuntu-vnc-desktop-opengl:
    build:
      context: ./
      dockerfile: ./Dockerfile
    privileged: true
    ports:
      - 5900:5900
      - 8081:8081
    volumes:
      - /dev/shm:/dev/shm
      - ./home:/root
    environment:
      - TZ=Asia/Tokyo
      - X11VNC_PORT=5900
      - NOVNC_PORT=8081
      - RESOLUTION=1600x900
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [display]